services:
  rsassistant:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    container_name: RSAssistant
    env_file:
      - ../.env  # Explicitly load the .env file
    volumes:
      - ../config:/app/config
      - ../volumes/logs:/app/volumes/logs
      - ../volumes/db:/app/volumes/db
      - ../volumes/excel:/app/volumes/excel